language: ruby
rvm:
- 2.3.3

install: 
- gem install bundler jekyll
- npm install -g firebase-tools bower
script: 
- bundle install
- bower install
- bundle exec jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages # Or `gh-pages`
